services:
  db:
    image: postgres:17
    container_name: gh_actions_test_db
    environment:
      POSTGRES_DB: gha_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: GenrH43f4Df4
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: api/.
    container_name: api
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gha_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=GenrH43f4Df4
    depends_on:
      - db

volumes:
  postgres-data: