name: demo.yaml
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6

      - name: Set Up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-deps-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle-wrapper.properties') }}

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Run Test
        run: ./api/gradlew -p api clean test

  build:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      jar-file: ${{ steps.publish.outputs.jar-file }}
    steps:
      - name: Get Code
        uses: actions/checkout@v6

      - name: Set Up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-deps-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle-wrapper.properties') }}

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build project
        run: ./api/gradlew -p api clean build -x test

      - name: Publish JAR file
        id: publish
        run: find api/build/libs/*SNAPSHOT.jar -type f -execdir echo 'jar-file={}' >> $GITHUB_OUTPUT ';'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: dist-files
          path: |
            api/build/libs
            api/build/reports

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v6
        with:
          name: dist-files

      - name: Log Files Containing Checkup
        run: ls -R

      - name: Output filename
        run: echo "${{ needs.build.outputs.jar-file }}"

      - name: Mock Deploy Code
        run: |
          echo 'Simulating deploy into an external host provider for training CI/CD using GitHub Actions'
          for i in $(seq 10 10 100); do echo $i%; done
          echo 'Mock deploy is done'